name: gateflow
description: Guard-first visitor management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP Client
  dio: ^5.4.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Logging
  logger: ^2.1.0

  # Confetti for success micro-interaction
  confetti: ^0.7.0

  # Links
  url_launcher: ^6.2.5

  # UI
  cupertino_icons: ^1.0.6

  #photo
  image_picker: ^1.1.2


  http: ^1.2.2
  http_parser: ^4.0.2

  flutter_animate: ^4.5.0
  phosphor_flutter: ^2.1.0
  shimmer: ^3.0.0

  # Push Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  
  # Firebase Auth & Firestore
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/.env
